# Author: Trenton W. Ford
# E-mail: tford5@nd.edu
#
# This is the Makefile for Programming Challenge 08

# CC is for the gcc compiler for C
CC := g++

# CXXFLAGS are the required compiler flags for the CSE 20133 course
CXXFLAGS := -m64 -std=c++11 -Weffc++ -O2 -Wall -Wextra -Wconversion -Wshadow -Werror -lm

# the make commands for problem1 are here to help you model the ones you'll write
#problem1: problem1.o
#	$(CC) $(CXXFLAGS) -o problem1 problem1.o
#
#problem1.o: problem1.c
#	$(CC) $(CXXFLAGS) -c problem1.c

clean:
	rm -rf a.out *.o problem1
