# Author: Trenton W. Ford
# E-mail: tford5@nd.edu
#
# This is the Makefile for Programming Challenge 04

# CC is for the gcc compiler for C
CC := gcc

# CFLAGS are the required compiler flags for the CSE 20133 course
CFLAGS := -Wall -Wextra -Wconversion -Werror -lm

# the make commands for problem1 are here to help you model the ones you'll write
#problem1: problem1.o
#	$(CC) $(CFLAGS) -o problem1 problem1.o
#
#problem1.o: problem1.c
#	$(CC) $(CFLAGS) -c problem1.c

clean:
	rm -rf a.out *.o problem1
