# Author: Trenton W. Ford
# E-mail: tford5@nd.edu
#
# This is the Makefile for Programming Challenge 01

# CC is for the gcc compiler for C
CC := gcc

# CFLAGS are the required compiler flags for the CSE 20133 course
CFLAGS := -Wall -Wextra -Wconversion -Werror -lm


# Compilation for the problem1 program
# Command: make problem1
problem1: problem1.o
	$(CC) $(CFLAGS) -o problem1 problem1.o

problem1.o: problem1.c
	$(CC) $(CFLAGS) -c problem1.c


# Compilation for the problem2 program
# Command: make problem2
problem2: problem2.o
	$(CC) $(CFLAGS) -o problem2 problem2.o

problem2.o: problem2.c
	$(CC) $(CFLAGS) -c problem2.c


# Compilation for the problem3 program
# Command: make problem3
problem3: problem3.o
	$(CC) $(CFLAGS) -o problem3 problem3.o

problem3.o: problem3.c
	$(CC) $(CFLAGS) -c problem3.c


# Compilation for the problem4 program
# Command: make problem4
problem4: problem4.o
	$(CC) $(CFLAGS) -o problem4 problem4.o

problem4.o: problem4.c
	$(CC) $(CFLAGS) -c problem4.c


# Compilation for the problem5 program
# Command: make problem5
problem5: problem5.o
	$(CC) $(CFLAGS) -o problem5 problem5.o

problem5.o: problem5.c
	$(CC) $(CFLAGS) -c problem5.c

# Compilation for the problem6 program
# Command: make problem6
problem6: problem6.o
	$(CC) $(CFLAGS) -o problem6 problem6.o

problem6.o: problem6.c
	$(CC) $(CFLAGS) -c problem6.c

# Compilation for the problem7 program
# Command: make problem7
problem7: problem7.o
	$(CC) $(CFLAGS) -o problem7 problem7.o

problem7.o: problem7.c
	$(CC) $(CFLAGS) -c problem7.c

# Compilation for the problem8 program
# Command: make problem8
problem8: problem8.o
	$(CC) $(CFLAGS) -o problem8 problem8.o

problem8.o: problem8.c
$(CC) $(CFLAGS) -c problem8.c

# Compilation for the problem9 program
# Command: make problem9
problem9: problem9.o
	$(CC) $(CFLAGS) -o problem9 problem9.o

problem9.o: problem9.c
	$(CC) $(CFLAGS) -c problem9.c

# Compilation for the problem10 program
# Command: make problem10
problem10: problem10.o
	$(CC) $(CFLAGS) -o problem10 problem10.o

problem10.o: problem10.c
	$(CC) $(CFLAGS) -c problem10.c

# Compilation for the problem10 program
# Command: make problem10
problem11: problem11.o
	$(CC) $(CFLAGS) -o problem11 problem11.o

problem11.o: problem11.c
	$(CC) $(CFLAGS) -c problem11.c

clean:
	rm -rf a.out *.o problem1 problem2 problem3 problem4 problem5 problem6 problem7 problem8 problem9 problem10 problem11
